# Generated by Django 4.2.27 on 2026-01-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("threads", "0002_alter_question_receiver_alter_question_sender"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_anonymous",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="question",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="reply",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
