# Generated by Django 6.0.1 on 2026-01-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0003_question_is_anonymous_alter_question_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='Untitled Question', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
