# Generated by Django 4.2.27 on 2026-01-30 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0004_question_title_question_views_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['created_at'], 'verbose_name': 'Reply', 'verbose_name_plural': 'Replies'},
        ),
    ]
